create table
  public.users (
    user_id integer generated by default as identity,
    user_type integer not null,
    username text not null,
    password text not null,
    time_sign_up timestamp with time zone not null default (now() at time zone 'utc'::text),
    constraint users_pkey primary key (user_id)
  ) tablespace pg_default;

create table
  public.performers (
    performer_id integer generated by default as identity,
    name text not null,
    capacity_preference integer null,
    time_available timestamp with time zone not null,
    time_end timestamp with time zone not null,
    constraint performers_pkey primary key (performer_id)
  ) tablespace pg_default;

create table
  public.venues (
    venue_id integer generated by default as identity,
    name timestamp with time zone not null default now(),
    location text not null,
    capacity integer not null,
    price integer not null,
    time_available timestamp with time zone not null,
    time_end timestamp with time zone not null,
    constraint venues_pkey primary key (venue_id)
  ) tablespace pg_default;

create table
  public.bookings (
    id integer generated by default as identity,
    performer_id integer not null,
    venue_id integer not null,
    time_start timestamp with time zone not null,
    time_end timestamp with time zone not null,
    constraint bookings_pkey primary key (id)
  ) tablespace pg_default;